name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Create SSH config
        run: |
          echo "Host bastion
            HostName ${{ secrets.BASTION_HOST }}
            User ${{ secrets.BASTION_USER }}
            Port 6883
            PasswordAuthentication yes
            ProxyCommand sshpass -p '${{ secrets.BASTION_PASSWORD }}' ssh -W %h:%p bastion" > ~/.ssh/config

      - name: Deploy to server through bastion
        run: |
          echo "
            cd /var/www/st.student-rescource
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
          " > deploy_script.sh

          # Kết nối đến máy chủ thật mà không cần chỉ định cổng
          sshpass -p "${{ secrets.TARGET_PASSWORD }}" ssh -tt -o StrictHostKeyChecking=no ${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }} 'bash -s' < deploy_script.sh
