name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to server through bastion
        run: |
          sshpass -p "${{ secrets.BASTION_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 6883 -o ProxyCommand="sshpass -p '${{ secrets.BASTION_PASSWORD }}' ssh -W %h:%p -p 6883 -o StrictHostKeyChecking=no ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }}" ${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }} << 'EOF'
            cd /var/www/your-app
            git pull origin main
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            sudo systemctl restart httpd
          EOF
