name: Check Laravel Pint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-scripts

      - name: Run Laravel Pint
        run: vendor/bin/pint --test
